name: bswfa_ui
description: "Battle Simulator War For Arrakis"
publish_to: 'none'
version: 1.0.1+11

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.32.5 <4.0.0'

dependencies:
  bswfa_core:
    path: ../../packages/bswfa_core
  
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_html: ^3.0.0
  freezed_annotation: ^3.0.0
  package_info_plus: ^8.3.0
  nested: any

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
flutter:
  uses-material-design: true
