name: bswfa
description: "Battle Simulator War For Arrakis"
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.22.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-beta.2
  freezed_annotation: ^2.4.3
  json_annotation: 4.9.0
  package_info_plus: ^8.0.0
  rxdart: ^0.28.0
  stream_transform: ^2.1.0
  wheel_chooser: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/presentation/assets

