name: bswfa
description: "Battle Simulator War For Arrakis"
publish_to: 'none'
version: 1.0.1+9
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.22.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-beta.2
  freezed_annotation: ^2.4.3
  package_info_plus: ^8.0.0
  nested: any
dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
flutter:
  uses-material-design: true
