name: bswfa_core
description: "Core Battle Simulator War For Arrakis"
publish_to: 'none'

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.0.6
