name: bswfa_core
description: "Core Battle Simulator War For Arrakis"
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.3

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
